### ISSUE TITLE
Some issues about box decode

### ISSUE THREAD

**Issue by xiaohu2015** [xiaochus/YOLOv3#1]
I found that you use:
        col = np.tile(np.arange(1, grid_w + 1), grid_w).reshape(-1, grid_w)
        row = np.tile(np.arange(1, grid_h + 1).reshape(-1, 1), grid_h)

It means you use offsets of [1, W] and [1, H], But why you not use [0, W-1] and [0, H-1]?

**Comment by xiaochus** [comment]
It should be [0, w-1] according to the implementation of the source code. But when i using the weight values provided by the author, there will be a grid of deviations, the result will be normal after add 1 in grid index. I haven't figured out why this happened. It may be that there is an error in the author's trained weight file.

**Comment by xiaohu2015** [comment]
@xiaochus The problem has been found. You can ref to this issues: [Keras-Yolov3](https://github.com/qqwweee/keras-yolo3/issues/8#event-1583141091).

**Comment by xiaochus** [comment]
@xiaohu2015 Thanks, the problem was fixed!
