### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by xiaosuzhang** [xiaochus/YOLOv3#3]
When i convert my own trained yolov3.weights to .h5, the error will shown as follows:
Traceback (most recent call last):
  File "yad2k.py", line 275, in <module>
    _main(parser.parse_args())
  File "yad2k.py", line 151, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

How to solve this problem
Thanks!

**Comment by xiaochus** [comment]
@xiaosuzhang The conversion program is based on the cfg file provided by the author. If your network structure is different from the original, you should use your own cfg file.
